version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=22-bookworm
    working_dir: /node
    volumes:
      - type: bind
        source: ../
        target: /node
      - type: tmpfs
        target: /node/docs
    tty: true
