name: Rhodonite Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: Rhodonite-distribution-files
        path: dist
    - run: npm run build-samples
    - run: npm run test
    - uses: actnwit/release-notes-generator@actnwit/supports-v0.x.x
      with:
        version: v0.4.2
        from_ref_exclusive: v0.4.1
        to_ref_inclusive: master
    - run: echo "${{ steps.release_notes.outputs.release_notes }}"
