name: Generate release notes
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits
          fetch-depth: 0
      - name: Generate release notes
        id: release_notes
        uses: fresa/release-notes-generator@v0.2.3
        with:
          version: v0.5.0
          from_ref_exclusive: v0.4.1
          to_ref_inclusive: master
      - run: echo "${{ steps.release_notes.outputs.release_notes }}"
